---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      filters: wall,stat,slf4j
      poolPreparedStatements: true
      stat-view-servlet:
        login-username: csp
        login-password: CSP@druid
  rabbitmq:
    publisher-confirms: false
    virtual-host: /
mybatis:
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
    
--- # 开发配置定义
spring:
  profiles: dev
  rabbitmq:
    host: 10.24.10.174
    port: 54402
    username: guest
    password: guest
  datasource:
    url: jdbc:oracle:thin:@10.24.10.224:1521:bdcor5
    username: csp
    password: develop
queueName: csp/web_dev
---
spring:
  profiles: test
  rabbitmq:
    host: 10.24.10.174
    port: 54402
    username: guest
    password: guest
  datasource:
    url: jdbc:oracle:thin:@10.24.10.224:1521:bdcor5
    username: csp
    password: develop
queueName: csp/web_test
---
spring:
  profiles: pro
  rabbitmq:
    host: 10.24.10.33
    port: 54402
    username: csp123321
    password: csp#123321
  datasource: 
    url: jdbc:oracle:thin:@10.24.10.34:1521:jtbiobank
    username: csp
    password: ncrc2017
queueName: csp/web_pro